# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 516d9526a60295f2bf65b5ec9b3635d373e323f9a4295f1a99e9d86fd5389055da1cffac6044927cfe908b0df58d64e46950f9638a297529565c0685289cc670

test:
  secret_key_base: d3df34c8e5615b9e24b857ff66a212bf653be14115f4963d106bf47dd4b81746f39d8a5b41cd70397967cb8e7cc17e5e32f45fc00cf5cd779b9fd8259035c737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
